# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def GenerateConstrainedTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ConstrainedTaskGraph:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateConstrainedTaskGraph", args={
            "in_arg": in_arg,
        })
        return typing.cast(types.ConstrainedTaskGraph, result.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TaskGraph:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateTaskGraph", args={
            "in_arg": in_arg,
        })
        return typing.cast(types.TaskGraph, result.cast_to(types, types, stream_types, False, __runtime__))
    async def GetRegisteredWindow(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RegisteredWindow:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="GetRegisteredWindow", args={
            "in_arg": in_arg,
        })
        return typing.cast(types.RegisteredWindow, result.cast_to(types, types, stream_types, False, __runtime__))
    async def Hello(self, inp_txt: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="Hello", args={
            "inp_txt": inp_txt,
        })
        return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def RAG(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Response:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="RAG", args={
            "question": question,"context": context,
        })
        return typing.cast(types.Response, result.cast_to(types, types, stream_types, False, __runtime__))
    async def TellAJokeV2(self, in_arg: types.StepFrameIn,
        baml_options: BamlCallOptions = {},
    ) -> types.StepFrameOut:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="TellAJokeV2", args={
            "in_arg": in_arg,
        })
        return typing.cast(types.StepFrameOut, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateConstrainedTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ConstrainedTaskGraph, types.ConstrainedTaskGraph]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateConstrainedTaskGraph", args={
            "in_arg": in_arg,
        })
        return baml_py.BamlStream[stream_types.ConstrainedTaskGraph, types.ConstrainedTaskGraph](
          result,
          lambda x: typing.cast(stream_types.ConstrainedTaskGraph, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ConstrainedTaskGraph, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GenerateTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.TaskGraph, types.TaskGraph]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateTaskGraph", args={
            "in_arg": in_arg,
        })
        return baml_py.BamlStream[stream_types.TaskGraph, types.TaskGraph](
          result,
          lambda x: typing.cast(stream_types.TaskGraph, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TaskGraph, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GetRegisteredWindow(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[types.RegisteredWindow, types.RegisteredWindow]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GetRegisteredWindow", args={
            "in_arg": in_arg,
        })
        return baml_py.BamlStream[types.RegisteredWindow, types.RegisteredWindow](
          result,
          lambda x: typing.cast(types.RegisteredWindow, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RegisteredWindow, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def Hello(self, inp_txt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="Hello", args={
            "inp_txt": inp_txt,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def RAG(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Response, types.Response]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="RAG", args={
            "question": question,"context": context,
        })
        return baml_py.BamlStream[stream_types.Response, types.Response](
          result,
          lambda x: typing.cast(stream_types.Response, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Response, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def TellAJokeV2(self, in_arg: types.StepFrameIn,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.StepFrameOut, types.StepFrameOut]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="TellAJokeV2", args={
            "in_arg": in_arg,
        })
        return baml_py.BamlStream[stream_types.StepFrameOut, types.StepFrameOut](
          result,
          lambda x: typing.cast(stream_types.StepFrameOut, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.StepFrameOut, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def GenerateConstrainedTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateConstrainedTaskGraph", args={
            "in_arg": in_arg,
        }, mode="request")
        return result
    async def GenerateTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateTaskGraph", args={
            "in_arg": in_arg,
        }, mode="request")
        return result
    async def GetRegisteredWindow(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GetRegisteredWindow", args={
            "in_arg": in_arg,
        }, mode="request")
        return result
    async def Hello(self, inp_txt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="Hello", args={
            "inp_txt": inp_txt,
        }, mode="request")
        return result
    async def RAG(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RAG", args={
            "question": question,"context": context,
        }, mode="request")
        return result
    async def TellAJokeV2(self, in_arg: types.StepFrameIn,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="TellAJokeV2", args={
            "in_arg": in_arg,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def GenerateConstrainedTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateConstrainedTaskGraph", args={
            "in_arg": in_arg,
        }, mode="stream")
        return result
    async def GenerateTaskGraph(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateTaskGraph", args={
            "in_arg": in_arg,
        }, mode="stream")
        return result
    async def GetRegisteredWindow(self, in_arg: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GetRegisteredWindow", args={
            "in_arg": in_arg,
        }, mode="stream")
        return result
    async def Hello(self, inp_txt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="Hello", args={
            "inp_txt": inp_txt,
        }, mode="stream")
        return result
    async def RAG(self, question: str,context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RAG", args={
            "question": question,"context": context,
        }, mode="stream")
        return result
    async def TellAJokeV2(self, in_arg: types.StepFrameIn,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="TellAJokeV2", args={
            "in_arg": in_arg,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))