# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def JokeTeller(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="JokeTeller", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def SampleInput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StepFrameIn:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SampleInput", llm_response=llm_response, mode="request")
        return typing.cast(types.StepFrameIn, result)

    def SampleOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StepFrameOut:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SampleOutput", llm_response=llm_response, mode="request")
        return typing.cast(types.StepFrameOut, result)

    def TellAJoke(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MonikerStepFrameOut:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TellAJoke", llm_response=llm_response, mode="request")
        return typing.cast(types.MonikerStepFrameOut, result)

    def TellAJokeV2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StepFrameOut:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TellAJokeV2", llm_response=llm_response, mode="request")
        return typing.cast(types.StepFrameOut, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def JokeTeller(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="JokeTeller", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def SampleInput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StepFrameIn:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SampleInput", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StepFrameIn, result)

    def SampleOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StepFrameOut:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SampleOutput", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StepFrameOut, result)

    def TellAJoke(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MonikerStepFrameOut:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TellAJoke", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MonikerStepFrameOut, result)

    def TellAJokeV2(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StepFrameOut:
        result = self.__options.merge_options(baml_options).parse_response(function_name="TellAJokeV2", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StepFrameOut, result)

    