# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (7)
# #########################################################################

class MonikerData(BaseModel):
    topic: typing.Optional[str] = None

class MonikerGuidance(BaseModel):
    topic: typing.Optional[str] = None
    style: typing.Optional[str] = None

class MonikerState(BaseModel):
    topic: typing.Optional[str] = None
    last_style: typing.Optional[str] = None
    last_output: typing.Optional[str] = None

class MonikerStepFrameIn(BaseModel):
    step: typing.Optional[str] = None
    state: typing.Optional["MonikerState"] = None
    guidance: typing.Optional["MonikerGuidance"] = None

class MonikerStepFrameOut(BaseModel):
    step: typing.Optional[str] = None
    state: typing.Optional["MonikerState"] = None
    next_step: typing.Optional[str] = None
    text: typing.Optional[str] = None
    data: typing.Optional["MonikerData"] = None
    done: typing.Optional[bool] = None
    notes: typing.Optional[str] = None

class StepFrameIn(BaseModel):
    context: typing.Optional[str] = None
    guidance: typing.Optional[str] = None

class StepFrameOut(BaseModel):
    status: typing.Optional[types.GenericStepOutStatus] = None
    control: typing.Optional[types.GenericStepOutControl] = None
    reason: typing.Optional[str] = None
    hint: typing.Optional[str] = None
    text: typing.Optional[str] = None
    payload: typing.Optional[str] = None
    context_delta: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
