# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Completion": types.Completion,
    "stream_types.Completion": stream_types.Completion,

    "types.ConstrainedTask": types.ConstrainedTask,
    "stream_types.ConstrainedTask": stream_types.ConstrainedTask,

    "types.ConstrainedTaskGraph": types.ConstrainedTaskGraph,
    "stream_types.ConstrainedTaskGraph": stream_types.ConstrainedTaskGraph,

    "types.DataEdge": types.DataEdge,
    "stream_types.DataEdge": stream_types.DataEdge,

    "types.Port": types.Port,
    "stream_types.Port": stream_types.Port,

    "types.Response": types.Response,
    "stream_types.Response": stream_types.Response,

    "types.StepFrameIn": types.StepFrameIn,
    "stream_types.StepFrameIn": stream_types.StepFrameIn,

    "types.StepFrameOut": types.StepFrameOut,
    "stream_types.StepFrameOut": stream_types.StepFrameOut,

    "types.Task": types.Task,
    "stream_types.Task": stream_types.Task,

    "types.TaskGraph": types.TaskGraph,
    "stream_types.TaskGraph": stream_types.TaskGraph,


    "types.CompletionPolicy": types.CompletionPolicy,

    "types.ExecutionMode": types.ExecutionMode,

    "types.GenericStepOutControl": types.GenericStepOutControl,

    "types.GenericStepOutStatus": types.GenericStepOutStatus,

    "types.RegisteredWindow": types.RegisteredWindow,

    "types.TaskType": types.TaskType,

}