# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.MonikerData": types.MonikerData,
    "stream_types.MonikerData": stream_types.MonikerData,

    "types.MonikerGuidance": types.MonikerGuidance,
    "stream_types.MonikerGuidance": stream_types.MonikerGuidance,

    "types.MonikerState": types.MonikerState,
    "stream_types.MonikerState": stream_types.MonikerState,

    "types.MonikerStepFrameIn": types.MonikerStepFrameIn,
    "stream_types.MonikerStepFrameIn": stream_types.MonikerStepFrameIn,

    "types.MonikerStepFrameOut": types.MonikerStepFrameOut,
    "stream_types.MonikerStepFrameOut": stream_types.MonikerStepFrameOut,

    "types.Response": types.Response,
    "stream_types.Response": stream_types.Response,

    "types.StepFrameIn": types.StepFrameIn,
    "stream_types.StepFrameIn": stream_types.StepFrameIn,

    "types.StepFrameOut": types.StepFrameOut,
    "stream_types.StepFrameOut": stream_types.StepFrameOut,


    "types.GenericStepOutControl": types.GenericStepOutControl,

    "types.GenericStepOutStatus": types.GenericStepOutStatus,

}